all:
	cl /std:c++17 wxtry.cpp /Fe:wxtry.exe kernel32.lib user32.lib gdi32.lib comdlg32.lib winspool.lib winmm.lib shell32.lib shlwapi.lib comctl32.lib ole32.lib oleaut32.lib uuid.lib rpcrt4.lib advapi32.lib version.lib ws2_32.lib wininet.lib oleacc.lib uxtheme.lib wxbase32u.lib wxmsw32u_core.lib wxbase32u_xml.lib nanosvg.lib nanosvgrast.lib libpng16.lib zlib.lib 
